### ISSUE TITLE
Quite new with this new front-end workflow. Having many problems

### ISSUE THREAD

**Issue by picwellwisher12pk** [madebysource/pho-devstack#64]
I am fan of Source team, your projects and own many products by Source. When I saw Pho-devstack. I was too much inspired by it. I think Pho-devstack is doing more than others like Fast-shell and Fire-shell etc. 

When I started using Pho-devstack, I faced many problems like Sass, are not being compiled , sometimes only main sass file is being compiled. Other sass files are not be processed and copied to dist directory etc.  At times I noticed , Gulp is acting strange and not reflecting the latest changes, or showing the changes that I did 3 or 4 steps behind, where I had removed a style-sheet file but gulp is currently showing and using the old file. 

Eventually I started using css , but I wish I could use Sass with Pho-devstack. May be it is me who do not understand all the things.

**Comment by picwellwisher12pk** [comment]
It looks like gulp-sass can't keep up with latest Sass. You should think about that too please.

**Comment by PavelGavlik** [comment]
Do these problems happen randomly or is there a pattern? Could you maybe post minimal configuration with these symptoms?

**Comment by picwellwisher12pk** [comment]
I am happy to give all the information. But I just don't know what you need to diagnose the issues.

**Comment by PavelGavlik** [comment]
Right. I need the configuration from `yo pho`, contents of gulpfile.js and recursive list of src/ directory.

**Comment by picwellwisher12pk** [comment]
During installation I got these errors.


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


bower cached        git://github.com/angular/bower-angular.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular.git#~1.2.9
bower install       angular#1.2.28

angular#1.2.28 src/bower_components/angular
npm WARN package.json sass@0.0.0 No description
npm WARN package.json sass@0.0.0 No README data
npm WARN deprecated gulp-clean@0.2.4: use gulp-rimraf instead
npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN deprecated ngmin@0.5.0: use ng-annotate instead
npm ERR! addRemoteGit Failed to change folder ownership under npm cache for /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-3baa7ac4
npm ERR! git clone --template=/home/amir/.npm/_git-remotes/_templates --mirror git@github.com:pipobscure/fsevents.git /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac
npm ERR! git clone --template=/home/amir/.npm/_git-remotes/_templates --mirror git@github.com:pipobscure/fsevents.git /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac: Cloning into bare repository '/home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac'...
npm ERR! git clone --template=/home/amir/.npm/_git-remotes/_templates --mirror git@github.com:pipobscure/fsevents.git /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac: Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
npm ERR! git clone --template=/home/amir/.npm/_git-remotes/_templates --mirror git@github.com:pipobscure/fsevents.git /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac: Permission denied (publickey).
npm ERR! git clone --template=/home/amir/.npm/_git-remotes/_templates --mirror git@github.com:pipobscure/fsevents.git /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/amir/.npm/_git-remotes/_templates --mirror git@github.com:pipobscure/fsevents.git /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac: 
npm ERR! git clone --template=/home/amir/.npm/_git-remotes/_templates --mirror git@github.com:pipobscure/fsevents.git /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/amir/.npm/_git-remotes/_templates --mirror git@github.com:pipobscure/fsevents.git /home/amir/.npm/_git-remotes/git-github-com-pipobscure-fsevents-git-7a888cac: and the repository exists.
npm WARN optional dep failed, continuing fsevents@git+https://github.com/pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138
npm WARN optional dep failed, continuing fsevents@0.3.6
 
> gmsmith@0.4.5 preinstall /home/amir/projects/sass/node_modules/pho-devstack/node_modules/gulp-sprites-preprocessor/node_modules/sprites-preprocessor/node_modules/spritesmith/node_modules/gmsmith
> gm -version || convert -version

sh: 1: gm: not found
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP    

 
> phantomjssmith@0.4.6 preinstall /home/amir/projects/sass/node_modules/pho-devstack/node_modules/gulp-sprites-preprocessor/node_modules/sprites-preprocessor/node_modules/spritesmith/node_modules/phantomjssmith
> phantomjs --version

sh: 1: phantomjs: not found
npm WARN optional dep failed, continuing phantomjssmith@0.4.6
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
 
> canvas@1.1.6 install /home/amir/projects/sass/node_modules/pho-devstack/node_modules/gulp-sprites-preprocessor/node_modules/sprites-preprocessor/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/home/amir/projects/sass/node_modules/pho-devstack/node_modules/gulp-sprites-preprocessor/node_modules/sprites-preprocessor/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node: Finished
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:19:0:
../src/JPEGStream.h:10:21: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
                     ^
compilation terminated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory `/home/amir/projects/sass/node_modules/pho-devstack/node_modules/gulp-sprites-preprocessor/node_modules/sprites-preprocessor/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-52-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
cwd /home/amir/projects/sass/node_modules/pho-devstack/node_modules/gulp-sprites-preprocessor/node_modules/sprites-preprocessor/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
 
> jpegtran-bin@0.2.8 postinstall /home/amir/projects/sass/node_modules/pho-devstack/node_modules/gulp-imagemin/node_modules/image-min/node_modules/jpegtran-bin
> node index.js

npm WARN optional dep failed, continuing canvassmith@0.2.4
 
> gifsicle@0.1.7 postinstall /home/amir/projects/sass/node_modules/pho-devstack/node_modules/gulp-imagemin/node_modules/image-min/node_modules/gifsicle
> node index.js

**Comment by picwellwisher12pk** [comment]
This is happening again and again. I m trying with Instagram , when I try to upload some photo , it gives above error and crashes.

**Comment by PavelGavlik** [comment]
Sadly, this is quite normal installation log. Optional dependencies fail quite often. But it shouldn't affect anything Sass-related. Does the `gulp` command output something wierd?
